name: PostgreSQL Service Workflow

on:
  push:

jobs:
  postgres-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps:
      - name: Check PostgreSQL readiness with nc
        run: |
          echo "⏳ Waiting for PostgreSQL to become available..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "✅ PostgreSQL is ready!"
              exit 0
            fi
            echo "⏱️ Attempt $i: PostgreSQL not ready yet..."
            sleep 1
          done
          echo "❌ PostgreSQL did not become ready in time."
          exit 1

