name: PostgreSQL Service Workflow

on:
  push:

jobs:
  postgres-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          while ! nc -z postgres 5432; do
            echo " Still waiting for PostgreSQL"
            sleep 1
          done
          echo "PostgreSQL is ready!"

