name: PostgreSQL Service Workflow

on:
  push:

jobs:
  postgres-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Checking PostgreSQL service availability..."
          for i in {1..30}; do
            nc -z localhost 5432 && echo "✅ PostgreSQL is ready!" && exit 0
            echo "⏳ Waiting for PostgreSQL..."
            sleep 1
          done
          echo "❌ PostgreSQL did not become ready in time."
          exit 1

